version: '3.8'

services:
  auth:
    build:
      context: ./auth_microservice
      dockerfile: Dockerfile
    ports:
      - "8080:8080" # Expose port 8080 to the host
    depends_on:
      - db # Wait for the database to start
    environment:
      SPRING_PROFILES_ACTIVE: prod
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: demo_db
      DB_USER: postgres
      DB_PASSWORD: 12345678

  pms:
    build:
      context: ./prod_mng_microservice
      dockerfile: Dockerfile
    ports:
      - "8082:8082" # Expose port 8082 to the host
    depends_on:
      - db # Wait for the database to start
    environment:
      SPRING_PROFILES_ACTIVE: prod
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: demo_db
      DB_USER: postgres
      DB_PASSWORD: 12345678

  db:
    image: postgres:14 # PostgreSQL image
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345678
      POSTGRES_DB: demo_db
    ports:
      - "5432:5432" # Expose PostgreSQL port
    volumes:
      - postgres_data:/var/lib/postgresql/data # Persist database data

volumes:
  postgres_data:
